version: '3.8'

services:
  app:
    build: .  # Construi a imagem do Docker com base no Dockerfile no diretorio atual
    container_name: codeigniter_app  # Nome do container para o servico da aplicacao
    restart: always  # Reinicia o container automaticamente se ele falhar
    ports:
      - "8080:80"  # Mapeia a porta 80 do container para a porta 8080 do host
    volumes:
      - .:/var/www/html  # Mapeia o diretorio atual do host para o diretorio do container
    depends_on:
      - db  # O servico app depende do servico db (banco de dados)
    environment:
      - DB_HOST=db  # Configura a variável de ambiente DB_HOST com o nome do servico db
      - DB_USER=postgres  # Usuário do banco de dados
      - DB_PASSWORD=secret  # Senha do banco de dados
      - DB_NAME=escola  # Nome do banco de dados

  db:
    image: postgres:13  # Usa a imagem oficial do Postgres na versao 13
    container_name: postgres_db  # Nome do container para o banco de dados
    restart: always  # Reinicia o container automaticamente se ele falhar
    environment:
      POSTGRES_USER: postgres  # Define o usuario do Postgres
      POSTGRES_PASSWORD: secret  # Define a senha do Postgres
      POSTGRES_DB: escola  # Nome do banco de dados que sera criado
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do container para a porta 5432 do host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mapeia um volume para persistir os dados do banco de dados

volumes:
  postgres_data:  # Define um volume nomeado para persistir os dados do banco de dados
